#!/bin/bash


# $1 = 2.81G
# $2 = 69%
# $3 = 330.67MB/s
# $4 = 0:00:03

(
awk '{
print "XXX"
print $2+0
print "Transferred data -> " $1
print $2 " done"
print "Speed -> " $3
print "Time left -> " $4
print "XXX"
}' < <(rsync -ah --info=progress2 "$@" |& stdbuf -i0 -o0 -e0 tr '\r' '\n' )
) | dialog --title "rsync $*" --gauge rsync 10 45 0






